sudo: false

language: scala

jdk: oraclejdk8

scala:
  - 2.12.7

branches:
  only:
    - fix_auto_version_issue

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalafmtCheck scalafmtSbtCheck

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

before_deploy:
  # unencrypt creds
  - openssl aes-256-cbc
      -K $encrypted_dcc5d8de5fcf_key -iv $encrypted_dcc5d8de5fcf_iv
      -in .travis/secrets.tar.enc -out .travis/local.secrets.tar -d;
      tar xv -C .travis -f .travis/local.secrets.tar
  # set up GitHub deployment ssh
  - declare -r TMP_GITHUB_SSH="$(mktemp -u $HOME/.ssh/XXXXX)";
      cp .travis/local.github_deploy_key $TMP_GITHUB_SSH;
      chmod 600 "$TMP_GITHUB_SSH"
       && printf "%s\n"
            "Host github.com"
            "  IdentityFile $TMP_GITHUB_SSH"
            "  LogLevel ERROR" >> ~/.ssh/config
  # use GitHub ssh repo
  - git remote set-url origin git@github.com:dmateusp/fs2-aws.git

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - git checkout fix_auto_version_issue;
          sbt ++$TRAVIS_SCALA_VERSION "release with-defaults"

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
