version: "2"
services:
  minio:
    image: minio/minio
    network_mode: host
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    command: server /data

  createbuckets:
    image: minio/mc
    network_mode: host
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add testminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY --api S3v4;
      /usr/bin/mc mb testminio/resources;
      /usr/bin/mc policy download testminio/resources;
      exit 0;
      "
  localstack:
    image: localstack/localstack:0.12.11
    network_mode: host
    ports:
      - 4566:4566
    environment:
      - "AWS_ACCESS_KEY_ID=dummy"
      - "AWS_SECRET_ACCESS_KEY=dummy"
      - "SERVICES=sqs,sns,kinesis,cloudwatch,dynamodb"
      - "DEFAULT_REGION=us-east-1"
      - "USE_SSL=true"
    volumes:
      - "./scripts/localstack:/docker-entrypoint-initaws.d"

